apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      containers:
      - name: backend
        image: marcosoliveirateixeira/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
